# pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "GoldSpace"
version = "0.1.0"
authors = [
  { name="jijh", email="your.email@example.com" },
]
description = "A research project for SpaGLaM, including open_clip_training and a dedicated preprocessing pipeline."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
# Dependencies for the SpaGLaM preprocessing package
preproc_models = ["open-clip-torch"]
preproc_wsi = ["openslide-python"]
preproc_squidpy = ["squidpy"]
preproc_notebook = ["matplotlib", "ipython", "jupyter"]
preproc_all = [
    "spaglam-preproc[preproc_models]",
    "spaglam-preproc[preproc_wsi]",
    "spaglam-preproc[preproc_squidpy]",
    "spaglam-preproc[preproc_notebook]",
]

[project.scripts]
spaglam-preproc = "spaglam_preproc.cli:app"
